version: '3.8'

services:
  server:
    build: ./
    command: ./wait-for-postgres.sh db ./trade-bot
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432

  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf