// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"
	models "trade-bot/internal/pkg/models"
	types "trade-bot/internal/pkg/tradeAlgorithm/types"
	krakenFuturesSDK "trade-bot/pkg/krakenFuturesSDK"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthorization is a mock of Authorization interface.
type MockAuthorization struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationMockRecorder
}

// MockAuthorizationMockRecorder is the mock recorder for MockAuthorization.
type MockAuthorizationMockRecorder struct {
	mock *MockAuthorization
}

// NewMockAuthorization creates a new mock instance.
func NewMockAuthorization(ctrl *gomock.Controller) *MockAuthorization {
	mock := &MockAuthorization{ctrl: ctrl}
	mock.recorder = &MockAuthorizationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorization) EXPECT() *MockAuthorizationMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockAuthorization) CreateUser(user models.User) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthorizationMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthorization)(nil).CreateUser), user)
}

// GenerateJWT mocks base method.
func (m *MockAuthorization) GenerateJWT(username, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJWT", username, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJWT indicates an expected call of GenerateJWT.
func (mr *MockAuthorizationMockRecorder) GenerateJWT(username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJWT", reflect.TypeOf((*MockAuthorization)(nil).GenerateJWT), username, password)
}

// GetUserAPIKeys mocks base method.
func (m *MockAuthorization) GetUserAPIKeys(userID int) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAPIKeys", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserAPIKeys indicates an expected call of GetUserAPIKeys.
func (mr *MockAuthorizationMockRecorder) GetUserAPIKeys(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAPIKeys", reflect.TypeOf((*MockAuthorization)(nil).GetUserAPIKeys), userID)
}

// GetUserIDByJWT mocks base method.
func (m *MockAuthorization) GetUserIDByJWT(token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByJWT", token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByJWT indicates an expected call of GetUserIDByJWT.
func (mr *MockAuthorizationMockRecorder) GetUserIDByJWT(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByJWT", reflect.TypeOf((*MockAuthorization)(nil).GetUserIDByJWT), token)
}

// LogoutUser mocks base method.
func (m *MockAuthorization) LogoutUser(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutUser", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogoutUser indicates an expected call of LogoutUser.
func (mr *MockAuthorizationMockRecorder) LogoutUser(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutUser", reflect.TypeOf((*MockAuthorization)(nil).LogoutUser), token)
}

// MockKrakenOrdersManager is a mock of KrakenOrdersManager interface.
type MockKrakenOrdersManager struct {
	ctrl     *gomock.Controller
	recorder *MockKrakenOrdersManagerMockRecorder
}

// MockKrakenOrdersManagerMockRecorder is the mock recorder for MockKrakenOrdersManager.
type MockKrakenOrdersManagerMockRecorder struct {
	mock *MockKrakenOrdersManager
}

// NewMockKrakenOrdersManager creates a new mock instance.
func NewMockKrakenOrdersManager(ctrl *gomock.Controller) *MockKrakenOrdersManager {
	mock := &MockKrakenOrdersManager{ctrl: ctrl}
	mock.recorder = &MockKrakenOrdersManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKrakenOrdersManager) EXPECT() *MockKrakenOrdersManagerMockRecorder {
	return m.recorder
}

// SendOrder mocks base method.
func (m *MockKrakenOrdersManager) SendOrder(userID int, args krakenFuturesSDK.SendOrderArguments) (models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOrder", userID, args)
	ret0, _ := ret[0].(models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendOrder indicates an expected call of SendOrder.
func (mr *MockKrakenOrdersManagerMockRecorder) SendOrder(userID, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOrder", reflect.TypeOf((*MockKrakenOrdersManager)(nil).SendOrder), userID, args)
}

// StartTrading mocks base method.
func (m *MockKrakenOrdersManager) StartTrading(ctx context.Context, userID int, details types.TradingDetails) (models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTrading", ctx, userID, details)
	ret0, _ := ret[0].(models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTrading indicates an expected call of StartTrading.
func (mr *MockKrakenOrdersManagerMockRecorder) StartTrading(ctx, userID, details interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTrading", reflect.TypeOf((*MockKrakenOrdersManager)(nil).StartTrading), ctx, userID, details)
}
